on:
  workflow_call:
    inputs:
      image:
        description: Image name
        required: true
        type: string
      tag:
        description: Image tag to build
        required: true
        type: string
      context:
        description: Docker build context
        type: string
        default: .
      checkout-ref:
        description: Custom ref to check out
        type: string
        default: ""
      submodules:
        # see https://github.com/actions/checkout
        default: "false"
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:
      GH_PAT:

jobs:
  build:
    uses: ./.github/workflows/dockerfile.yml
    with:
      image: ${{ inputs.image }}
      tag: ${{ inputs.tag }}
      context: ${{ inputs.context }}
      checkout-ref: ${{ inputs.checkout-ref }}
      submodules: ${{ inputs.submodules }}
      push: false
      notify-failure: false
    # secrets: inherit
    # passing on secrets via inherit seems to be no longer possible
    # if this workflow is included from a foreign organisation
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
