on:
  workflow_call:
    inputs:
      notify-failure:
        description: Notify on build failure to Slack
        default: true
        type: boolean
      image:
        description: Image name
        required: true
        type: string
      tag:
        description: Image tag to build
        required: true
        type: string
      push:
        description: If the image should be pushed
        type: boolean
        default: false
      context:
        description: Docker build context
        type: string
        default: .
      checkout-ref:
        description: Custom ref to check out
        type: string
        default: ''
    secrets:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:
      SLACK_NOTIFICATIONS_BOT_TOKEN:

jobs:
  run:
    runs-on: ${{ vars.CUSTOM_RUNNER || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ${{ inputs.image }}

      - name: Login to DockerHub
        if: env.DOCKER_HUB_USERNAME
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          tags: "${{ inputs.image }}:${{ inputs.tag }}"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Vulnerability check
        uses: wetransform/gha-trivy@647b4e7c5a0b87529d0241afa9f22ca97d8d6a26 # v2.3.7
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.tag }}"
          create-test-report: true
          report-retention-days: 30

      #
      # Report build failure to Slack
      #

        # https://github.com/marketplace/actions/slack-notify-build
      - name: Notify slack fail
        if: ${{ inputs.notify-failure && failure() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        with:
          channel: build-failures
          status: FAILED
          color: danger
