on:
  workflow_call:
    inputs:
      image:
        description: Image name
        required: true
        type: string
      tag:
        description: Image tag to build
        required: true
        type: string
      context:
        description: Docker build context
        type: string
        default: .
    secrets:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:

jobs:
  build:
    uses: ./.github/workflows/dockerfile.yml
    with:
      image: ${{ inputs.image }}
      tag: ${{ inputs.tag }}
      context: ${{ inputs.context }}
      push: false
      notify-failure: false
    secrets: inherit
