on:
  workflow_call:
    inputs:
      notify-failure:
        description: Notify on build failure to Slack
        default: true
        type: boolean
      image:
        description: Image name
        required: true
        type: string
      tag:
        description: Image tag to build
        required: true
        type: string
      push:
        description: If the image should be pushed
        type: boolean
        default: false
      context:
        description: Docker build context
        type: string
        default: .
      checkout-ref:
        description: Custom ref to check out
        type: string
        default: ""
    secrets:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:
      SLACK_NOTIFICATIONS_BOT_TOKEN:

jobs:
  run:
    runs-on: ${{ vars.CUSTOM_RUNNER || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ${{ inputs.image }}

      - name: Login to DockerHub
        if: env.DOCKER_HUB_USERNAME
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          tags: "${{ inputs.image }}:${{ inputs.tag }}"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Vulnerability check
        uses: wetransform/gha-trivy@706acc9132d4c9f1b09b3613fd6b4fa904e52bf3 # v2.5.2
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.tag }}"
          create-test-report: true
          report-retention-days: 30

      #
      # Report build failure to Slack
      #

      # https://github.com/marketplace/actions/slack-notify-build
      - name: Notify slack fail
        if: ${{ inputs.notify-failure && failure() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        with:
          channel: build-failures
          status: FAILED
          color: danger
