on:
  workflow_call:
    inputs:
      notify-failure:
        description: Notify on build failure to Slack
        default: true
        type: boolean
      image:
        description: Image name
        required: true
        type: string
      tag:
        description: Image tag to build
        required: true
        type: string
      push:
        description: If the image should be pushed
        type: boolean
        default: false
      context:
        description: Docker build context
        type: string
        default: .
    secrets:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:
      SLACK_NOTIFICATIONS_BOT_TOKEN:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: ${{ inputs.image }}

      - name: Login to DockerHub
        if: env.DOCKER_HUB_USERNAME
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build and push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          tags: "${{ inputs.image }}:${{ inputs.tag }}"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Vulnerability check
        uses: wetransform/gha-trivy@master
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.tag }}"
          create-test-report: true
          report-retention-days: 30

      #
      # Report build failure to Slack
      #

        # https://github.com/marketplace/actions/slack-notify-build
      - name: Notify slack fail
        if: ${{ inputs.notify-failure && failure() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@a16c99c8c65bf5de29482033b665fb8656ba99a0 # v1
        with:
          channel: build-failures
          status: FAILED
          color: danger
