on:
  workflow_call:
    inputs:
      gradle-tasks:
        description: Custom Gradle tasks to run
        required: false
        type: string
        default: ''
      java-version:
        description: Java version to use for build
        required: true
        type: string
      image-tag:
        description: Image tag to scan after build
        required: true
        type: string
      image-tag-2:
        description: Additional image tag to scan after build
        type: string
        default: ''
      image-tag-3:
        description: Additional image tag to scan after build
        type: string
        default: ''
      multi-module:
        description: If this is a multi-module project
        type: boolean
        default: false
    secrets:
      # GH_PAT:
      #   required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_EMAIL:
      WETF_ARTIFACTORY_USER:
      WETF_ARTIFACTORY_PASSWORD:
      ENV_VARS: # secret for passing on additional env variables based on https://github.com/orgs/community/discussions/26671#discussioncomment-6776498

jobs:
  check:
    uses: ./.github/workflows/gradle-service.yml
    with:
      gradle-tasks: ${{ inputs.gradle-tasks != '' && inputs.gradle-tasks || 'clean check dockerTagLatest' }}
      java-version: ${{ inputs.java-version }}
      image-tag: ${{ inputs.image-tag }}
      image-tag-2: ${{ inputs.image-tag-2 }}
      image-tag-3: ${{ inputs.image-tag-3 }}
      multi-module: ${{ inputs.multi-module }}
      notify-failure: false
    secrets: inherit
