on:
  workflow_call:
    inputs:
      gradle-tasks:
        description: Custom Gradle tasks to run
        required: false
        type: string
        default: ''
      java-version:
        description: Java version to use for build
        required: true
        type: string
      image-tag:
        description: Image tag to scan after build
        required: true
        type: string
      image-tag-2:
        description: Additional image tag to scan after build
        type: string
        default: ''
      image-tag-3:
        description: Additional image tag to scan after build
        type: string
        default: ''
      multi-module:
        description: If this is a multi-module project
        type: boolean
        default: false
      expect-tests:
        description: If JUnit test results are expected
        default: true
        type: boolean
      submodules:
        # see https://github.com/actions/checkout
        default: 'false'
        type: string
      checkout-ref:
        description: Custom ref to check out
        type: string
        default: ''
    secrets:
      GH_PAT:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:
      DOCKER_HUB_EMAIL:
      WETF_ARTIFACTORY_USER:
      WETF_ARTIFACTORY_PASSWORD:
      ENV_VARS: # secret for passing on additional env variables based on https://github.com/orgs/community/discussions/26671#discussioncomment-6776498

jobs:
  check:
    uses: ./.github/workflows/gradle-service.yml
    with:
      build-tasks: ${{ inputs.gradle-tasks != '' && inputs.gradle-tasks || 'clean check dockerTagLatest' }}
      java-version: ${{ inputs.java-version }}
      image-tag: ${{ inputs.image-tag }}
      image-tag-2: ${{ inputs.image-tag-2 }}
      image-tag-3: ${{ inputs.image-tag-3 }}
      multi-module: ${{ inputs.multi-module }}
      expect-tests: ${{ inputs.expect-tests }}
      submodules: ${{ inputs.submodules }}
      checkout-ref: ${{ inputs.checkout-ref }}
      notify-failure: false
    # secrets: inherit
    # passing on secrets via inherit seems to be no longer possible
    # if this workflow is included from a foreign organisation
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_EMAIL: ${{ secrets.DOCKER_HUB_EMAIL }}
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
      ENV_VARS: ${{ secrets.ENV_VARS }}
