#
# Mise workflow for running a task
#
# Conventions:
# - workflow uses mise environment "ci"
# - runs a specific mise task (run-task input)
# - if an environment variable IMAGE_NAME is set by mise or the build, a security scan will be performed on the image
# - if a file docker-bake.hcl is present, the Docker image will be built using docker bake and it should not be built by the mise task;
#   in this case IMAGE_NAME is expected to be a name without tag and tags to build are determined automatically
# - the docker-bake.hcl should have a target named "default", it should inherit from an empty target "docker-metadata-action"
#
# Variants:
# - npm: Cache Node.js modules
#

on:
  workflow_call:
    inputs:
      run-task:
        description: mise task to run
        required: true
        type: string
      publish:
        description: If the task is a publish task (sets PUBLISH_VERSION environment variable)
        required: false
        default: false
        type: boolean
      variant:
        description: Workflow variant to use (leave empty or use one of 'npm')
        required: true
        type: string
      parallel:
        description: Run mise tasks in parallel (true) or sequentially (false)
        required: false
        default: false
        type: boolean
      default-branch:
        description: Name of the default branch (e.g. 'main' or 'master')
        required: false
        default: master
        type: string
      default-version:
        description: Version string to use for the default branch (e.g. 'latest')
        required: false
        default: latest
        type: string
      notify-failure:
        description: Notify on build failure to Slack
        default: true
        type: boolean
      skip-scan:
        description: If security scan and associated tasks should be skipped
        type: boolean
        default: false
      submodules:
        # see https://github.com/actions/checkout
        default: 'false'
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
      DOCKER_HUB_PASSWORD:
      GH_PAT:
      SLACK_NOTIFICATIONS_BOT_TOKEN:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      #
      # Determine what to check out and what version to build
      #
      - name: Determine ref to checkout and version
        if: ${{ inputs.publish }}
        id: version
        run: |
          DEFAULT_BRANCH="${{ inputs.default-branch }}"
          DEFAULT_VERSION="${{ inputs.default-version }}"

          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" && -n "${{ github.event.inputs.version }}" ]]; then
            REF="refs/tags/v${{ github.event.inputs.version }}"
            VERSION="${{ github.event.inputs.version }}"
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            REF="${GITHUB_REF}"
            VERSION="${GITHUB_REF#refs/tags/v}"
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            REF="${GITHUB_REF}"
            if [[ "$BRANCH_NAME" == "$DEFAULT_BRANCH" ]]; then
              VERSION="$DEFAULT_VERSION"
            else
              VERSION="$BRANCH_NAME"
            fi
          else
            # fallback
            REF="refs/heads/${DEFAULT_BRANCH}"
            VERSION="$DEFAULT_VERSION"
          fi
          echo "ref=$REF" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          echo "PUBLISH_VERSION=$VERSION" >> $GITHUB_ENV

      #
      # Checkout source code
      #
      - name: Checkout specific ref
        if: ${{ inputs.publish }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ steps.version.outputs.ref }}
          submodules: ${{ inputs.submodules }}
          # provide a token in case submodules are enabled and private (secret is expected to be present)
          token: ${{ inputs.submodules != 'false' && secrets.GH_PAT || github.token }}
      - name: Checkout code
        if: ${{ !inputs.publish }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: ${{ inputs.submodules }}
          # provide a token in case submodules are enabled and private (secret is expected to be present)
          token: ${{ inputs.submodules != 'false' && secrets.GH_PAT || github.token }}

      #
      # Setup mise & tools
      #
      - name: Setup mise & tools
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1

      #
      # Optional login to Docker Hub
      #
      - name: Login to DockerHub
        if: env.DOCKER_HUB_USERNAME
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      #
      # npm: Cache Node.js modules
      #
      - name: Cache Node.js modules
        if: ${{ inputs.variant == 'npm' }}
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run mise task
        # Run mise tasks in parallel or sequentially based on input
        run: |
          TASK_NAME="${{ inputs.run-task }}"
          if [ "${{ inputs.parallel }}" = "true" ]; then
            mise run ${TASK_NAME}
          else
            mise run --raw ${TASK_NAME}
          fi
        env:
          MISE_ENV: ci
          # required for some builds, set if available
          GH_PAT: ${{ secrets.GH_PAT }}

      #
      # Check if docker-bake.hcl is present and if so, build the Docker image
      #

      - name: Check for docker-bake.hcl
        if: ${{ env.IMAGE_NAME }}
        id: check_docker_bake
        run: |
          if [ -f docker-bake.hcl ]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Docker metadata
        id: meta
        if: steps.check_docker_bake.outputs.found == 'true'
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            # Fixed tag for security scan
            type=raw,value=ci
            # Use latest for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Use version when building for tag
            type=semver,pattern={{version}}
            type=semver,pattern=v{{major}}
            # Use tag for branch name
            type=ref,event=branch

      - name: Build Docker image including metadata labels
        if: steps.check_docker_bake.outputs.found == 'true'
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: default
          load: true # needed for scanning
          push: ${{ inputs.publish }}

      #
      # Custom test reports
      #

      - name: Extract JUnit report paths from config
        id: extract_report_paths
        run: |
          if [ -f .wetf-ci.yml ]; then
            paths=$(yq e '.test["report-paths"] | select(. != null) | join("\n")' .wetf-ci.yml)
          else
            paths=""
          fi
          echo "paths<<EOF" >> $GITHUB_OUTPUT
          echo "$paths" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish test report
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
        if: ${{ steps.extract_report_paths.outputs.paths != '' && always() }}
        with:
          report_paths: ${{ steps.extract_report_paths.outputs.paths }}
          require_tests: ${{ !inputs.publish }} # for publish we may not have tests
          annotate_only: true
          detailed_summary: true
          fail_on_failure: true # in case of critical security vulnerabilities, also required for Slack notification if only tests fail

      #
      # Security scans
      # Env variable IMAGE_NAME must be set by mise or the build to scan a Docker image
      #

      # Determine image name to scan
      - name: Determine image name to scan
        if: ${{ !inputs.skip-scan && env.IMAGE_NAME }}
        id: image_name
        run: |
          if [ -f docker-bake.hcl ]; then
            # if using bake we assume IMAGE_NAME is a name without tag and we need to append the fixed tag "ci"
            IMAGE_NAME="${{ env.IMAGE_NAME }}:ci"
          else
            IMAGE_NAME="${{ env.IMAGE_NAME }}"
          fi
          echo "SCAN_IMAGE=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Make sure scan result folder exists
        if: ${{ !inputs.skip-scan }}
        run: mkdir -p trivy-gha-scan

      - name: Vulnerability scan (repo)
        if: ${{ !inputs.skip-scan }}
        uses: wetransform/gha-trivy@314d7180e7198c35b302e178ae299a14a1a73c36 # v2.4.0
        with:
          junit-test-output: "trivy-gha-scan/repo.xml" # added to unit test report
          report-retention-days: 30
          report-tag: repository

      - name: Vulnerability scan (image)
        if: ${{ !inputs.skip-scan && env.SCAN_IMAGE }}
        uses: wetransform/gha-trivy@314d7180e7198c35b302e178ae299a14a1a73c36 # v2.4.0
        with:
          image-ref: 'docker.io/${{ env.SCAN_IMAGE }}'
          junit-test-output: "trivy-gha-scan/image.xml" # added to unit test report
          report-retention-days: 30
          report-tag: ${{ env.SCAN_IMAGE }}

        # https://github.com/marketplace/actions/junit-report-action
      - name: Publish scan report
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
        if: ${{ !inputs.skip-scan && always() }} # always run even if the previous step fails
        with:
          report_paths: "trivy-gha-scan/*.xml"
          require_tests: false # there may be no vulnerabilities found, then there is no file

          # Workaround for check that is additionally created being associated
          # to the wrong workflow/run. Instead not additional check is created.
          # See https://github.com/mikepenz/action-junit-report/issues/40
          annotate_only: true
          detailed_summary: true
          fail_on_failure: true # in case of critical security vulnerabilities, also required for Slack notification if only tests fail

      #
      # Report build failure to Slack
      # https://github.com/marketplace/actions/slack-notify-build
      #
      - name: Notify slack fail
        if: ${{ inputs.notify-failure && failure() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        with:
          channel: build-failures
          status: FAILED
          color: danger
