on:
  workflow_call:
    inputs:
      commmand:
        description: Custom command to run for the build
        default: ''
        required: false
        type: string
      pre-build-command:
        description: Custom command to run before the build
        type: string
        default: ''
      java-version:
        description: Java version to use for build
        required: true
        type: string
      image-tag:
        description: Image tag to scan after build
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_EMAIL:
      WETF_ARTIFACTORY_USER:
      WETF_ARTIFACTORY_PASSWORD:
      SLACK_NOTIFICATIONS_BOT_TOKEN:

jobs:
  publish:
    uses: ./.github/workflows/play-service.yml
    with:
      command: ${{ inputs.command != '' && inputs.command || './sbt clean update test docker:publishLocal' }}
      pre-build-command: ${{ inputs.pre-build-command }}
      java-version: ${{ inputs.java-version }}
      image-tag: ${{ inputs.image-tag }}
      notify-failure: true
      push-image: true
    # secrets: inherit
    # passing on secrets via inherit seems to be no longer possible
    # if this workflow is included from a foreign organisation
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_EMAIL: ${{ secrets.DOCKER_HUB_EMAIL }}
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
