on:
  workflow_call:
    inputs:
      commmand:
        description: Custom command to run for the build
        default: ''
        required: false
        type: string
      pre-build-command:
        description: Custom command to run before the build
        type: string
        default: ''
      java-version:
        description: Java version to use for build
        required: true
        type: string
      expect-tests:
        description: If JUnit test results are expected
        default: true
        type: boolean
    secrets:
      WETF_ARTIFACTORY_USER:
      WETF_ARTIFACTORY_PASSWORD:

jobs:
  check:
    uses: ./.github/workflows/sbt-library.yml
    with:
      command: ${{ inputs.command != '' && inputs.command || './sbt clean update test +test' }}
      pre-build-command: ${{ inputs.pre-build-command }}
      java-version: ${{ inputs.java-version }}
      expect-tests: ${{ inputs.expect-tests }}
      notify-failure: false
    # secrets: inherit
    # passing on secrets via inherit seems to be no longer possible
    # if this workflow is included from a foreign organisation
    secrets:
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
